---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: test
  pull: default
  image: node:10
  commands:
  - scripts/ci
  when:
    event:
    - push
    - pull_request
    - tag

---
kind: pipeline
name: docker

platform:
  os: linux
  arch: amd64

steps:
- name: docker-image
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    tag: ${DRONE_BRANCH##release\/}
    repo: rancherlabs/dashboard
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/release/v*"
    event:
    - push

---
kind: pipeline
name: hosted
platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: node:10
  commands:
  - ./scripts/build-hosted
  when:
    event:
    - push
    - tag

- name: upload
  pull: default
  image: plugins/gcs
  settings:
    acl:
    - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: dist/${DRONE_BRANCH##release\/}
    target: releases.rancher.com/dashboard/${DRONE_BRANCH##release\/}
    token:
      from_secret: google_auth_key
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/release/v*"
    event:
    - push
    - tag

---
kind: pipeline
name: embedded
platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: node:10
  commands:
  - ./scripts/build-embedded
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/release/v*"
    event:
    - push
    - tag

- name: upload
  pull: default
  image: plugins/gcs
  settings:
    acl:
    - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: dist/${DRONE_BRANCH##release\/}.tar.gz
    target: releases.rancher.com/dashboard/
    token:
      from_secret: google_auth_key
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/release/v*"
    event:
    - push
    - tag
