---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: test
  pull: default
  image: node:10
  commands:
  - scripts/ci
  when:
    event:
    - push
    - pull_request
    - tag

---
kind: pipeline
name: docker-branch

platform:
  os: linux
  arch: amd64

steps:
- name: docker-image
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    tag: ${DRONE_BRANCH}
    repo: rancherlabs/dashboard
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/*-dev"
    event:
    - push

---
kind: pipeline
name: docker-tag

platform:
  os: linux
  arch: amd64

steps:
- name: docker-image
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    tag: ${DRONE_TAG}
    repo: rancherlabs/dashboard
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    ref:
      include:
      - "refs/tags/v*"
    event:
    - tag

---
kind: pipeline
name: hosted-branch
platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: node:10
  commands:
  - ./scripts/build-hosted
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/*-dev"
    event:
    - push

- name: upload
  pull: default
  image: plugins/gcs
  settings:
    acl:
    - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: dist/${DRONE_BRANCH}
    target: releases.rancher.com/dashboard/${DRONE_BRANCH}
    token:
      from_secret: google_auth_key
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/*-dev"
    event:
    - push

---
kind: pipeline
name: hosted-tag
platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: node:10
  commands:
  - ./scripts/build-hosted
  when:
    ref:
      include:
      - "refs/tags/*"
    event:
    - tag

- name: upload
  pull: default
  image: plugins/gcs
  settings:
    acl:
    - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: dist/${DRONE_TAG}
    target: releases.rancher.com/dashboard/${DRONE_TAG}
    token:
      from_secret: google_auth_key
  when:
    ref:
      include:
      - "refs/tags/*"
    event:
    - tag

---
kind: pipeline
name: embedded-branch
platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: node:10
  commands:
  - ./scripts/build-embedded
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/*-dev"
    event:
    - push

- name: upload
  pull: default
  image: plugins/gcs
  settings:
    acl:
    - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: dist/${DRONE_BRANCH}.tar.gz
    target: releases.rancher.com/dashboard/${DRONE_BRANCH}.tar.gz
    token:
      from_secret: google_auth_key
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/*-dev"
    event:
    - push

---
kind: pipeline
name: embedded-tag
platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: node:10
  commands:
  - ./scripts/build-embedded
  when:
    ref:
      include:
      - "refs/tags/*"
    event:
    - tag

- name: upload
  pull: default
  image: plugins/gcs
  settings:
    acl:
    - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: dist/${DRONE_TAG}.tar.gz
    target: releases.rancher.com/dashboard/${DRONE_TAG}.tar.gz
    token:
      from_secret: google_auth_key
  when:
    ref:
      include:
      - "refs/tags/*"
    event:
    - tag
