name: Build and Release Rancher Dashboard - Rancher Desktop Embed

on:
  push:
    branch:
      - 'feature/rancher-desktop-builds'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false
    
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    
    - name: Install & Build
      run: |
        yarn install --frozen-lockfile
        NUXT_ENV_commit=${GITHUB_SHA} NUXT_ENV_version=${GITHUB_REF_NAME} OUTPUT_DIR=dist/embed-rancher-desktop ROUTER_BASE='/dashboard' RANCHER_ENV=desktop yarn run build --spa
        
    - name: Upload Build
      uses: actions/upload-artifact@v2
      with:
        path: dist/embed-rancher-desktop
        if-no-files-found: error
