name: Build and Release Rancher Components

on:
  push:
    branches:
      - release/components/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false

    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Install
      run: yarn

    - name: Lint
      run: yarn lint:lib

    - name: Build
      run: yarn build:lib

    - name: Unit Test
      run: yarn test:ci ./pkg/rancher-components
